apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  silenceAutosupport: true
  tridentImage: netapp/trident:26.02.1
  imagePullSecrets:
  - thisisasecret
